/*
 * Copyright (C) 2026  zclei
 * This file is part of AET.

 * AET is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 3, or (at your option) any later
 * version.

 * AET is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.

 * You should have received a copy of the GNU General Public License
 * along with GCC Exception along with this program; see the file COPYING3.
 * If not see <http://www.gnu.org/licenses/>.
 * AET was originally developed  by the onlineaet@163.com
 * base on genconstants.cc
 */

/* This program does not use gensupport.cc because it does not need to
   look at insn patterns, only (define_constants), and we want to
   minimize dependencies.  */

#include "bconfig.h"
#include "system.h"
#include "coretypes.h"
#include "errors.h"
#include "statistics.h"
#include "vec.h"
#include "read-md.h"

#include "mtcsgen.h"

/* Called via traverse_md_constants; emit a #define for
   the current constant definition.  */

static int print_md_constant (void **slot, void *info ATTRIBUTE_UNUSED)
{
  struct md_constant *def = (struct md_constant *) *slot;
  char *platName=mtcs_gen_get_platform_name(mtcs_gen_get());

  if (!def->parent_enum)
    printf ("#define %s_%s %s\n", platName,def->name, def->value);
  return 1;
}

/* Called via traverse_enums.  Emit an enum definition for
   enum_type *SLOT.  */

static int
print_enum_type (void **slot, void *info ATTRIBUTE_UNUSED)
{
  struct enum_type *def;
  struct enum_value *value;
  char *value_name;
  char *platName=mtcs_gen_get_platform_name(mtcs_gen_get());
  char *platUpperName=mtcs_gen_get_platform_upper_name(mtcs_gen_get());

  def = (struct enum_type *) *slot;
  printf ("\nenum %s_%s {", platName,def->name);
  for (value = def->values; value; value = value->next){
      printf ("\n  %s_%s = %s", platUpperName,value->def->name, value->def->value);
      if (value->next)
         putc (',', stdout);
  }
  printf ("\n};\n");

  /* Define NUM_<enum>_VALUES to be the largest enum value + 1.  */
  value_name = ACONCAT (("num_", def->name, "_values", NULL));
  upcase_string (value_name);
  printf ("#define %s_%s %d\n", platUpperName,value_name, def->num_values);

  /* Declare the array that is generated by genenum.  */
  printf ("extern const char *const %s_%s_strings[];\n", platName,def->name);

  return 1;
}

/* Called via traverse_enum_types.  Emit an enum definition for
   enum_type *SLOT.  */

static int print_enum_type_strings (void **slot, void *info ATTRIBUTE_UNUSED)
{
  struct enum_type *def;
  struct enum_value *value;
  char *platName=mtcs_gen_get_platform_name(mtcs_gen_get());
  char *platUpperName=mtcs_gen_get_platform_upper_name(mtcs_gen_get());
  def = (struct enum_type *) *slot;
  printf ("\nconst char *const %s_%s_strings[] = {", platName,def->name);
  for (value = def->values; value; value = value->next)
    {
      printf ("\n  \"%s_%s\"", platUpperName,value->def->name);
      if (value->next)
   putc (',', stdout);
    }
  printf ("\n};\n");
  return 1;
}


int main (int argc, const char **argv)
{
  progname = "mtcsgenconstants";
  noop_reader reader;
  fprintf(stderr,"mtcsgenconstants 00 start %d\n",getpid());

  //原来是read_md_files加入回调mtcs_gen_handle_arg可以处理mtcs的特殊参数
  if (!reader.read_md_files (argc, argv, mtcs_gen_handle_arg_no_mode))
    return (FATAL_EXIT_CODE);
  fprintf(stderr,"mtcsgenconstants 11ss %s\n",argv[1]);

  char *platName=mtcs_gen_get_platform_name(mtcs_gen_get());
  char *platUpperName=mtcs_gen_get_platform_upper_name(mtcs_gen_get());
  char *outputCFile= mtcs_gen_get_c_file(mtcs_gen_get());
  fprintf(stderr,"mtcsgenconstants 11 %s\n",argv[2]);
  /* Initializing the MD reader has the side effect of loading up
     the constants table that we wish to scan.  */
  if(!outputCFile){
     puts ("/* Generated automatically by the program `mtcsgenconstants'");
     puts ("   from the machine description file `md'.  */\n");
     printf ("#ifndef __GCC_%s_INSN_UNSPEC_H__\n",platUpperName);
     printf ("#define __GCC_%s_INSN_UNSPEC_H__\n",platUpperName);

     reader.traverse_md_constants (print_md_constant, 0);
     reader.traverse_enum_types (print_enum_type, 0);

     printf ("\n#endif /* __GCC_%s_INSN_UNSPEC_H__ */\n",platUpperName);
  }else{
     puts ("/* Generated automatically by the program `mtcsgenconstants'");
     puts ("   from the machine description file.  */\n");
     puts ("#include \"config.h\"\n");
     puts ("#include \"system.h\"\n");
     printf ("#include \"%s-insn-unspec.h\"\n",platName);

     reader.traverse_enum_types (print_enum_type_strings, 0);
  }

  if (ferror (stdout) || fflush (stdout) || fclose (stdout))
    return FATAL_EXIT_CODE;

  return SUCCESS_EXIT_CODE;
}
