/*
 * Copyright (C) 2026  zclei
 * This file is part of AET.

 * AET is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 3, or (at your option) any later
 * version.

 * AET is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.

 * You should have received a copy of the GNU General Public License
 * along with GCC Exception along with this program; see the file COPYING3.
 * If not see <http://www.gnu.org/licenses/>.
 * AET was originally developed  by the onlineaet@163.com
 */

#include "config.h"
#define INCLUDE_ALGORITHM /* reverse */
#include "system.h"
#include "coretypes.h"
#include "backend.h"
#include "target.h"
#include "rtl.h"
#include "tree.h"
#include "tree-pass.h"
#include "cfghooks.h"
#include "df.h"
#include "memmodel.h"
#include "tm_p.h"
#include "insn-config.h"
#include "regs.h"
#include "emit-rtl.h"
#include "recog.h"
#include "cgraph.h"
#include "tree-pretty-print.h" /* for dump_function_header */
#include "varasm.h"
#include "insn-attr.h"
#include "conditions.h"
#include "flags.h"
#include "output.h"
#include "except.h"
#include "rtl-error.h"
#include "toplev.h" /* exact_log2, floor_log2 */
#include "reload.h"
#include "intl.h"
#include "cfgrtl.h"
#include "debug.h"
#include "tree-pass.h"
#include "tree-ssa.h"
#include "cfgloop.h"
#include "stringpool.h"
#include "attribs.h"
#include "asan.h"
#include "rtl-iter.h"
#include "print-rtl.h"
#include "function-abi.h"
#include "common/common-target.h"
#include "diagnostic.h"
#include "context.h"
#include "options.h"
#include "expmed.h"
#include "expr.h"
#include "fold-const.h"
#include "dwarf2out.h"
#include "common/common-targhooks.h"

#include "cfganal.h"
#include "cfgcleanup.h"
#include "alias.h"
#include "rtlhooks-def.h"
#include "tree-pass.h"
#include "dbgcnt.h"
#include "rtlanal.h"

#include "aet/aetprinttree.h"
#include "../mtcstarget.h"
#include "../mtcsmicro.h"
#include "../mtcsprintrtl.h"
#include "../../mtcsinfo.h"
#include "ptxtool.h"
#include "gen/ptx-insn-modes.h"
#include "mtcsptxoutput.h"
#include "mtcsptxasm.h"
#include "mtcsptxfunc.h"
#include "mtcsptxmode.h"
#include "mtcsptxoptions.h"
#include "mtcsptx.h"
#include "targetptxasmout.h"

static void nvptx_assemble_value (TargetPtxAsmOut *self,unsigned HOST_WIDE_INT val, unsigned size);

/* Emit to STREAM the assembler syntax for an insn operand whose memory
   address is X.  */
//原型targetm.asm_out.print_operand_address #define TARGET_PRINT_OPERAND_ADDRESS default_print_operand_address
static void printOperandAddress_cb(TargetAsmOut *targetAsmOut,machine_mode mode,  rtx addr ATTRIBUTE_UNUSED)
{
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(targetAsmOut);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsPtxOutput *mtcsPtxOutput=(MtcsPtxOutput *)mtcs_target_get_output(mtcsTarget);

   mtcs_ptx_output_print_address_operand (mtcsPtxOutput,addr, mode);
}

//原型targetm.asm_out.print_operand #define TARGET_PRINT_OPERAND default_print_operand
static void printOperand_cb(TargetAsmOut *targetAsmOut,rtx x ATTRIBUTE_UNUSED,int code ATTRIBUTE_UNUSED)
{
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(targetAsmOut);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsPtxOutput *mtcsPtxOutput=(MtcsPtxOutput *)mtcs_target_get_output(mtcsTarget);

   mtcs_ptx_output_print_operand(mtcsPtxOutput,x,code);
}

//写入一个标记，当汇编完成时，这个标记被引用的函数声明替换 fileEnd_cb
#define REPLACE_FUNC_DECL_LOCATION "// replace func decl"

//原型  targetm.asm_out.file_start ();#define TARGET_ASM_FILE_START nvptx_file_start
static void fileStart_cb(TargetAsmOut *targetAsmOut)
{
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(targetAsmOut);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsAsm *mtcsAsm=mtcs_target_get_asm(mtcsTarget);

   n_debug("targetptxasmout.c -----nvptx.cc -----50-- TARGET_ASM_FILE_START void nvptx_file_start (void) pid:%d\n",getpid());
   //
   // Generated by NVIDIA NVVM Compiler
   //
   // Compiler Build ID: CL-31442593
   // Cuda compilation tools, release 11.7, V11.7.99
   // Based on NVVM 7.0.1
   //
   fputs("//\n",mtcsAsm->asmFile);
   fputs("//Generated by AET Compiler\n",mtcsAsm->asmFile);
   fputs("//\n",mtcsAsm->asmFile);

   PtxVersion version=mtcs_target_get_version(mtcsTarget);
   const char *verStre= ptx_tool_version_to_string(version);
   PtxIsa isa= mtcs_target_get_isa(mtcsTarget);
   const char *isaStr = ptx_tool_sm_version_to_string(isa);

   fputs ("\t.version\t", mtcsAsm->asmFile);
   fputs (verStre,mtcsAsm->asmFile);
   fputs ("\n", mtcsAsm->asmFile);

   fputs ("\t.target\tsm_", mtcsAsm->asmFile);
   fprintf (mtcsAsm->asmFile,"%s",isaStr);
   fputs ("\n", mtcsAsm->asmFile);
   unsigned short addressSize=mtcs_mode_get_bitsize(mtcsMode,mtcs_mode_get_Pmode(mtcsMode)/*MTCS_Pmode*/);
   fprintf (mtcsAsm->asmFile, "\t.address_size %d\n", addressSize/*GET_MODE_BITSIZE (MTCS_Pmode)*/);
   fputs ("\n", mtcsAsm->asmFile);
   //写入一个标记，当汇编完成时，这个标记被引用的函数声明替换 fileEnd_cb
   fputs (REPLACE_FUNC_DECL_LOCATION, mtcsAsm->asmFile);
}

/* Return true if TYPE is a record type where the last field is an array without
   given dimension.  */
static bool flexible_array_member_type_p (const_tree type)
{
   if (TREE_CODE (type) != RECORD_TYPE)
      return false;

   const_tree last_field = NULL_TREE;
   for (const_tree f = TYPE_FIELDS (type); f; f = TREE_CHAIN (f))
      last_field = f;

   if (!last_field)
      return false;

   const_tree last_field_type = TREE_TYPE (last_field);
   if (TREE_CODE (last_field_type) != ARRAY_TYPE)
      return false;

   return (! TYPE_DOMAIN (last_field_type) || ! TYPE_MAX_VALUE (TYPE_DOMAIN (last_field_type)));
}

/* Emit a linker marker for a variable decl or defn.  */
static void write_var_marker (TargetPtxAsmOut *self, bool is_defn, bool globalize, const char *name)
{
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(self);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsAsm *mtcsAsm=mtcs_target_get_asm(mtcsTarget);

   fprintf (mtcsAsm->asmFile, "\n// BEGIN%s VAR %s: ", globalize ? " GLOBAL" : "",is_defn ? "DEF" : "DECL");
   mtcs_asm_assemble_name_raw (mtcsAsm, name);
   fputs ("\n", mtcsAsm->asmFile);
}

/* Emit a PTX variable decl and prepare for emission of its
   initializer.  NAME is the symbol name and SETION the PTX data
   area. The type is TYPE, object size SIZE and alignment is ALIGN.
   The caller has already emitted any indentation and linkage
   specifier.  It is responsible for any initializer, terminating ;
   and newline.  SIZE is in bytes, ALIGN is in bits -- confusingly
   this is the opposite way round that PTX wants them!  */
static void nvptx_assemble_decl_begin (TargetPtxAsmOut *self, const char *name, const char *section,
               const_tree type, HOST_WIDE_INT size, unsigned align, bool undefined = false)
{
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(self);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsAsm *mtcsAsm=mtcs_target_get_asm(mtcsTarget);
   MtcsTraverseTree *mtcsTraverseTree =mtcs_target_get_traverse_tree(mtcsTarget);

   n_debug("targetptxasmout.c -----nvptx.cc -----90-- void nvptx_assemble_decl_begin name:%s section:%s size:%d align:%d\n",
               name,section,size,align);
   bool atype = (TREE_CODE (type) == ARRAY_TYPE) && (TYPE_DOMAIN (type) == NULL_TREE);
   if (undefined && flexible_array_member_type_p (type)){
      size = 0;
      atype = true;
   }

   while (TREE_CODE (type) == ARRAY_TYPE)
      type = TREE_TYPE (type);

   if (TREE_CODE (type) == VECTOR_TYPE || TREE_CODE (type) == COMPLEX_TYPE)
      /* Neither vector nor complex types can contain the other.  */
      type = TREE_TYPE (type);

   unsigned HOST_WIDE_INT elt_size = int_size_in_bytes (type);
   n_debug("targetptxasmout.c -----nvptx.cc -----90aa-- elt_size:%d typeMode:%d %s\n",elt_size,TYPE_MODE (type),
               mtcs_mode_get_name(mtcsMode,TYPE_MODE (type)));
   aet_print_tree(type);
   /* Largest mode we're prepared to accept.  For BLKmode types we
   don't know if it'll contain pointer constants, so have to choose
   pointer size, otherwise we can choose DImode.  */
   mtcs_mode elt_mode =TYPE_MODE (type) == mtcsMode->modes.M_BLKmode ?mtcs_mode_get_Pmode(mtcsMode) :mtcsMode->modes.M_DImode;
   const char *ptx_type = mtcs_mode_get_type/*!nvptx_ptx_type_from_mode*/ (mtcsMode,TYPE_MODE (type), false);

   elt_size |= mtcs_mode_get_size/*GET_MODE_SIZE*/ (mtcsMode,elt_mode);
   elt_size &= -elt_size; /* Extract LSB set.  */
   n_debug("targetptxasmout.c -----nvptx.cc -----90bb-- name:%s size:%d elt_size:%d elt_mode:%d %s\n",name,size,elt_size,elt_mode,ptx_type);

   self->init_frag.size = elt_size;
   /* Avoid undefined shift behavior by using '2'.  */
   self->init_frag.mask = ((unsigned HOST_WIDE_INT)2 << (elt_size * BITS_PER_UNIT - 1)) - 1;
   self->init_frag.val = 0;
   self->init_frag.offset = 0;
   self->init_frag.started = false;
   /* Size might not be a multiple of elt size, if there's an
   initialized trailing struct array with smaller type than
   elt_size. */
   self->init_frag.remaining = (size + elt_size - 1) / elt_size;

   fprintf (mtcsAsm->asmFile, "%s .align %d .u" HOST_WIDE_INT_PRINT_UNSIGNED " ",section, align / BITS_PER_UNIT,elt_size * BITS_PER_UNIT);
   //fprintf (mtcsAsm->asmFile, "%s .align %d %s ",section, align / BITS_PER_UNIT,ptx_type);
   //输出变量名
   mtcs_asm_assemble_name (mtcsAsm, name);

   if (size)
      /* We make everything an array, to simplify any initialization
      emission.  */
      fprintf (mtcsAsm->asmFile, "[" HOST_WIDE_INT_PRINT_UNSIGNED "]", self->init_frag.remaining);
   else if (atype)
      fprintf (mtcsAsm->asmFile, "[]");
}

/* Called when the initializer for a decl has been completely output through
   combinations of the three functions above.  */
static void nvptx_assemble_decl_end (TargetPtxAsmOut *self)
{
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(self);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsAsm *mtcsAsm=mtcs_target_get_asm(mtcsTarget);

   n_debug("targetptxasmout.c -----nvptx.cc -----55-- TARGET_ASM_DECL_END void nvptx_assemble_decl_end (void)\n");
   if (self->init_frag.offset)
      /* This can happen with a packed struct with trailing array member.  */
      nvptx_assemble_value (self,0, self->init_frag.size - self->init_frag.offset);
   fprintf (mtcsAsm->asmFile, self->init_frag.started ? " };\n" : ";\n");
}

//原型 targetm.asm_out.declare_constant_name (asm_out_file, label, exp, size);
//#define TARGET_ASM_DECLARE_CONSTANT_NAME default_asm_declare_constant_name
//参见MtcsAsm 的 assembleConstantContents 输出到asmVarDecl。
static void declareConstantName_cb(TargetAsmOut *targetAsmOut,const char *name,
      const_tree exp ATTRIBUTE_UNUSED,HOST_WIDE_INT obj_size ATTRIBUTE_UNUSED)
{
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(targetAsmOut);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsAsm *mtcsAsm=mtcs_target_get_asm(mtcsTarget);

   n_debug("targetptxasmout.c -----nvptx.cc -----56-- TARGET_ASM_DECLARE_CONSTANT_NAME void name:%s %s obj_size:%d align:%d\n",
         name,get_tree_code_name(TREE_CODE(exp)),obj_size,TYPE_ALIGN (TREE_TYPE (exp)));

   write_var_marker((TargetPtxAsmOut *)targetAsmOut, true, false, name);
   fprintf (mtcsAsm->asmFile, "\t");
   tree type = TREE_TYPE (exp);
   nvptx_assemble_decl_begin((TargetPtxAsmOut *)targetAsmOut, name, ".global", type, obj_size, TYPE_ALIGN (type));
}

static void output_init_frag (TargetPtxAsmOut *self,rtx sym)
{
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(self);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsAsm *mtcsAsm=mtcs_target_get_asm(mtcsTarget);
   MtcsOutput *mtcsOutput=mtcs_target_get_output(mtcsTarget);

   fprintf (mtcsAsm->asmFile, self->init_frag.started ? ", " : " = { ");
   unsigned HOST_WIDE_INT val = self->init_frag.val;
   n_debug("targetptxasmout.c -----nvptx.cc -----180-- output_init_frag val:%d\n",val);

   self->init_frag.started = true;
   self->init_frag.val = 0;
   self->init_frag.offset = 0;
   self->init_frag.remaining--;

   if (sym){
      bool function = (SYMBOL_REF_DECL (sym)  && (TREE_CODE (SYMBOL_REF_DECL (sym)) == FUNCTION_DECL));
      if (!function)
         fprintf (mtcsAsm->asmFile, "generic(");
      mtcs_output_address (mtcsOutput,VOIDmode, sym);
      if (!function)
         fprintf (mtcsAsm->asmFile, ")");
      if (val)
         fprintf (mtcsAsm->asmFile, " + ");
   }

   if (!sym || val)
      fprintf (mtcsAsm->asmFile, HOST_WIDE_INT_PRINT_DEC, val);
}

/* Add value VAL of size SIZE to the data we're emitting, and keep
   writing out chunks as they fill up.  */
static void nvptx_assemble_value (TargetPtxAsmOut *self,unsigned HOST_WIDE_INT val, unsigned size)
{
   n_debug("targetptxasmout.c -----nvptx.cc -----53-- void nvptx_assemble_value val:%d size:%d\n",val,size);
   bool negative_p = val & (HOST_WIDE_INT_1U << (HOST_BITS_PER_WIDE_INT - 1));
   /* Avoid undefined behaviour.  */
   if (size * BITS_PER_UNIT < HOST_BITS_PER_WIDE_INT)
      val &= (HOST_WIDE_INT_1U << (size * BITS_PER_UNIT)) - 1;

   for (unsigned part = 0; size; size -= part){
      if (part * BITS_PER_UNIT == HOST_BITS_PER_WIDE_INT)
         /* Avoid undefined behaviour.  */
         val = negative_p ? -1 : 0;
      else
         val >>= (part * BITS_PER_UNIT);
      part = self->init_frag.size - self->init_frag.offset;
      part = MIN (part, size);

      unsigned HOST_WIDE_INT partial = val << (self->init_frag.offset * BITS_PER_UNIT);
      self->init_frag.val |= partial & self->init_frag.mask;
      self->init_frag.offset += part;
      if (self->init_frag.offset == self->init_frag.size)
         output_init_frag (self,NULL);
   }
}


//原型 TARGET_ASM_DECL_END 无缺省实现
static void declEnd_cb(TargetAsmOut *targetAsmOut)
{
   TargetPtxAsmOut *self=(TargetPtxAsmOut *)targetAsmOut;
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(self);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsAsm *mtcsAsm=mtcs_target_get_asm(mtcsTarget);

   n_debug("targetptxasmout.c -----nvptx.cc -----55-- TARGET_ASM_DECL_END void nvptx_assemble_decl_end (void)\n");
   if (self->init_frag.offset)
      /* This can happen with a packed struct with trailing array member.  */
      nvptx_assemble_value (self,0, self->init_frag.size - self->init_frag.offset);
   fprintf (mtcsAsm->asmFile, self->init_frag.started ? " };\n" : ";\n");
}

/* Implement TARGET_ASM_GLOBALIZE_LABEL by doing nothing. nvptx_globalize_label */
//原型targetm.asm_out.globalize_label (file, name); #define TARGET_ASM_GLOBALIZE_LABEL default_globalize_label
static void globalizeLabel_cb (TargetAsmOut *targetAsmOut,const char *name)
{
   n_debug("targetptxasmout.c -----nvptx.cc -----48-- TARGET_ASM_GLOBALIZE_LABEL 什么都不做 name:%s\n",name);
}

//原型  targetm.asm_out.print_operand_punct_valid_p ((unsigned char) *p) #define TARGET_PRINT_OPERAND_PUNCT_VALID_P nvptx_print_operand_punct_valid_p
static bool printOperandPunctValidP_cb(TargetAsmOut *targetAsmOut,unsigned char c)
{
   n_debug("targetptxasmout.c -----nvptx.cc -----181-- TARGET_PRINT_OPERAND_PUNCT_VALID_P bool nvptx_print_operand_punct_valid_p (unsigned char c)\n");
   return c == '.' || c== '#';
}

//原型 targetm.asm_out.file_end (); #define TARGET_ASM_FILE_END nvptx_file_end
static void fileEnd_cb(TargetAsmOut *targetAsmOut)
{
   TargetPtxAsmOut *self=(TargetPtxAsmOut *)targetAsmOut;
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(self);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsFunc *mtcsFunc=mtcs_target_get_func(mtcsTarget);
   MtcsPtxFunc *mtcsPtxFunc=(MtcsPtxFunc *)mtcsFunc;
   MtcsAsm *mtcsAsm=mtcs_target_get_asm(mtcsTarget);
   MtcsPtxOutput *mtcsPtxOutput=(MtcsPtxOutput *)mtcs_target_get_output(mtcsTarget);

   n_debug("targetptxasmout.c nvptx.cc nvptx_file_end 00 \n");
   mtcs_ptx_func_file_end(mtcsPtxFunc);
   //把extern 函数声明 写到文件前
   fclose(mtcsAsm->asmFile);

   //int seek= fseek(mtcsAsm->asmFile,0,SEEK_SET);
   FILE *sourceFile=fopen(mtcsAsm->asmFileName,"r");
   NString *brr=n_string_sized_new(2048*1024);
   int len=fread(brr->str,1,2048*1024,sourceFile);
   brr->str[len]='\0';
   brr->len=len;
   fclose(sourceFile);

   fclose(mtcsAsm->asmVarDeclFile);
   FILE *varDeclFile=fopen(mtcsAsm->asmVarDeclFileName,"r");
   char varDeclBuffer[1024*512];
   int  varDeclLen = fread(varDeclBuffer,1,1024*512,varDeclFile);
   varDeclBuffer[varDeclLen]='\0';
   fclose(varDeclFile);
   char *fndeclAsm=mtcs_ptx_asm_get_all_fun_decl_asm((MtcsPtxAsm *)mtcsAsm);
   NString *declStr=n_string_new("");
   if(fndeclAsm)
      n_string_append(declStr,fndeclAsm);
   if(varDeclLen>0)
      n_string_append(declStr,varDeclBuffer);
   //是否有.file 2 "xxxx.c"调试文件
   char *debgFile = mtcs_ptx_output_get_debug_file(mtcsPtxOutput);
   if(debgFile)
      n_string_append(declStr,debgFile);

   n_string_replace(brr,REPLACE_FUNC_DECL_LOCATION,declStr->str,1);
   mtcsAsm->asmFile=fopen(mtcsAsm->asmFileName,"w");
   fputs (brr->str, mtcsAsm->asmFile);
   n_string_free(brr,TRUE);
   n_string_free(declStr,TRUE);
}

///* The various PTX memory areas an object might reside in.  */
//enum nvptx_data_area
//{
//  DATA_AREA_GENERIC,
//  DATA_AREA_GLOBAL,
//  DATA_AREA_SHARED,
//  DATA_AREA_LOCAL,
//  DATA_AREA_CONST,
//  DATA_AREA_PARAM,
//  DATA_AREA_MAX
//};
//
///*  We record the data area in the target symbol flags.  */
//#define SYMBOL_DATA_AREA(SYM) \
//  (nvptx_data_area)((SYMBOL_REF_FLAGS (SYM) >> SYMBOL_FLAG_MACH_DEP_SHIFT) & 7)
//
//#define SET_SYMBOL_DATA_AREA(SYM,AREA) \
//  (SYMBOL_REF_FLAGS (SYM) |= (AREA) << SYMBOL_FLAG_MACH_DEP_SHIFT)

/* Return the PTX name of the data area in which SYM should be
   placed.  The symbol must have already been processed by
   nvptx_encode_seciton_info, or equivalent.  */

static const char * section_for_sym (rtx sym)
{
   ptx_data_area area = PTX_SYMBOL_DATA_AREA (sym);
   /* Same order as nvptx_data_area enum.  */
   static char const *const areas[] =
      {"", ".global", ".shared", ".local", ".const", ".param"};

   return areas[area];
}



/* Similarly for a decl.  */
static const char * section_for_decl (TargetPtxAsmOut *self,const_tree decl)
{
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(self);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsAsm *mtcsAsm=mtcs_target_get_asm(mtcsTarget);

   static char *managed = ".global .attribute(.managed)";
   const char *ret= section_for_sym (XEXP (mtcs_asm_decl_rtl/*!DECL_RTL*/(mtcsAsm,CONST_CAST (tree, decl)), 0));
   if(VAR_P(decl)){
      MtcsVarType varType = mtcs_info_get_var_type(decl);
      if(varType == MTCS_VAR_MANAGED && !strcmp(ret,".global"))
         return managed;
   }
   return ret;
}

/* Implement TARGET_ASM_ASSEMBLE_UNDEFINED_DECL.  Write an extern
   declaration only for variable DECL with NAME to FILE.  */
//原型 targetm.asm_out.assemble_undefined_decl (asm_out_file, name, decl);
//#define TARGET_ASM_ASSEMBLE_UNDEFINED_DECL nvptx_assemble_undefined_decl
static void assembleUndefinedDecl_cb (TargetAsmOut *targetAsmOut, const char *name, const_tree decl)
{
   TargetPtxAsmOut *self=(TargetPtxAsmOut *)targetAsmOut;
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(self);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsAsm *mtcsAsm=mtcs_target_get_asm(mtcsTarget);

   n_debug("targetptxasmout.c -----nvptx.cc -----49-- void nvptx_assemble_undefined_decl (FILE *file, const char *name, const_tree decl)\n");
   /* The middle end can place constant pool decls into the varpool as
   undefined.  Until that is fixed, catch the problem here.  */
   if (DECL_IN_CONSTANT_POOL (decl))
      return;
   /*  We support weak defintions, and hence have the right
   ASM_WEAKEN_DECL definition.  Diagnose the problem here.  */
   if (DECL_WEAK (decl))
      error_at (DECL_SOURCE_LOCATION (decl), "PTX does not support weak declarations (only weak definitions)");

   FILE *back=mtcsAsm->asmFile;
   mtcsAsm->asmFile=mtcsAsm->asmVarDeclFile;
   write_var_marker(self, false, TREE_PUBLIC (decl), name);
   fprintf (mtcsAsm->asmFile, "\t.extern ");
   tree size = DECL_SIZE_UNIT (decl);
   nvptx_assemble_decl_begin(self, name, section_for_decl(self,decl),
         TREE_TYPE (decl), size ? tree_to_shwi (size) : 0, DECL_ALIGN (decl), true);
   nvptx_assemble_decl_end(self);
   mtcsAsm->asmFile=back;
}

//原型 targetm.asm_out.integer#define TARGET_ASM_INTEGER nvptx_assemble_integer
static bool integer_cb(TargetAsmOut *targetAsmOut,rtx x ATTRIBUTE_UNUSED,
      unsigned int size ATTRIBUTE_UNUSED,int aligned_p ATTRIBUTE_UNUSED)
{
   TargetPtxAsmOut *self=(TargetPtxAsmOut *)targetAsmOut;
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(self);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsPtxFunc *mtcsPtxFunc=(MtcsPtxFunc *)mtcs_target_get_func(mtcsTarget);

   n_debug("targetptxasmout.c -----nvptx.cc -----54-- TARGET_ASM_INTEGER bool nvptx_assemble_integer \n");
   HOST_WIDE_INT val = 0;
   switch (GET_CODE (x)){
      default:
         /* Let the generic machinery figure it out, usually for a
         CONST_WIDE_INT.  */
         return false;

      case CONST_INT:
         nvptx_assemble_value(self,INTVAL (x), size);
         break;

      case CONST:
         x = XEXP (x, 0);
         gcc_assert (GET_CODE (x) == PLUS);
         val = INTVAL (XEXP (x, 1));
         x = XEXP (x, 0);
         gcc_assert (GET_CODE (x) == SYMBOL_REF);
         gcc_fallthrough (); /* FALLTHROUGH */

      case SYMBOL_REF:
         gcc_assert (size == self->init_frag.size);
         if (self->init_frag.offset)
            sorry ("cannot emit unaligned pointers in ptx assembly");
         mtcs_ptx_func_maybe_record_fnsym (mtcsPtxFunc,x);
         self->init_frag.val = val;
         output_init_frag(self,x);
         break;
   }

   return true;
}


//原型 targetm.asm_out.globalize_decl_name (asm_out_file, decl);#define TARGET_ASM_GLOBALIZE_DECL_NAME default_globalize_decl_name
static void globalizeDeclName_cb(TargetAsmOut *targetAsmOut,tree decl)
{
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(targetAsmOut);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsAsm *mtcsAsm=mtcs_target_get_asm(mtcsTarget);

   const char *name = XSTR (XEXP (mtcs_asm_decl_rtl/*!DECL_RTL*/(mtcsAsm,decl), 0), 0);
   target_asm_out_globalize_label/*targetm.asm_out.globalize_label*/(targetAsmOut, name);
}


/* Output SIZE zero bytes.  We ignore the FILE argument since the
   functions we're calling to perform the output just use
   asm_out_file.  */
//原型 #define ASM_OUTPUT_SKIP(FILE, N) nvptx有实现
static void outputSkip_cb (TargetAsmOut *targetAsmOut, unsigned HOST_WIDE_INT size)
{
   TargetPtxAsmOut *self=(TargetPtxAsmOut *)targetAsmOut;

   /* Finish the current fragment, if it's started.  */
   if (self->init_frag.offset){
      unsigned part = self->init_frag.size - self->init_frag.offset;
      part = MIN (part, (unsigned)size);
      size -= part;
      nvptx_assemble_value(self,0, part);
   }

   /* If this skip doesn't terminate the initializer, write as many
   remaining pieces as possible directly.  */
   if (size < self->init_frag.remaining * self->init_frag.size){
      while (size >= self->init_frag.size){
         size -= self->init_frag.size;
         output_init_frag(self,NULL_RTX);
      }
      if (size)
         nvptx_assemble_value(self,0, size);
   }
}

/**
 * 原型 #define ASM_OUTPUT_ALIGNED_DECL_COMMON(FILE, DECL, NAME, SIZE, ALIGN)   nvptx有实现
 * 未初始化的全局变量 int x; 进这里
 */
static void outputAlignedDeclCommon_cb(TargetAsmOut *targetAsmOut,const_tree decl, const char *name, HOST_WIDE_INT size, unsigned align)
{
   TargetPtxAsmOut *self=(TargetPtxAsmOut *)targetAsmOut;
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(self);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsAsm *mtcsAsm=mtcs_target_get_asm(mtcsTarget);

   FILE *back=mtcsAsm->asmFile;
   mtcsAsm->asmFile=mtcsAsm->asmVarDeclFile;
   n_debug("targetptxasmout.c  -----nvptx.cc -----176-- nvptx_output_aligned_decl 未初始化的全局变量:%s align:%d size:%d\n",name,align,size);
   write_var_marker(self, true, TREE_PUBLIC (decl), name);
   /* If this is public, it is common.  The nearest thing we have to
   common is weak.  */
   fprintf (mtcsAsm->asmFile, "\t%s", TREE_PUBLIC (decl) ? ".weak " : "");
   nvptx_assemble_decl_begin(self, name, section_for_decl (self,decl),TREE_TYPE (decl), size, align);
   nvptx_assemble_decl_end(self);
   mtcsAsm->asmFile=back;
}

//原型 #define ASM_DECLARE_OBJECT_NAME(FILE, NAME, DECL)  nvptx_declare_object_name (FILE, NAME, DECL)
//参见MtcsVar assemble_variable_contents 方法，输出到asmVarDeclFile。
static void declareObjectName_cb(TargetAsmOut *targetAsmOut, const char *name, const_tree decl)
{
   TargetPtxAsmOut *self=(TargetPtxAsmOut *)targetAsmOut;
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(self);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsAsm *mtcsAsm=mtcs_target_get_asm(mtcsTarget);

   n_debug("targetptxasmout.c -----nvptx.cc -----87-- void nvptx_declare_object_name \n");
   write_var_marker(self, true, TREE_PUBLIC (decl), name);
   fprintf (mtcsAsm->asmFile, "\t%s", (!TREE_PUBLIC (decl) ? "": DECL_WEAK (decl) ? ".weak " : ".visible "));
   tree type = TREE_TYPE (decl);
   aet_print_tree(type);
   HOST_WIDE_INT obj_size = tree_to_shwi (DECL_SIZE_UNIT (decl));
   nvptx_assemble_decl_begin(self, name, section_for_decl (self,decl),type, obj_size, DECL_ALIGN (decl));
}

/*
static int x = 1;      // 文件作用域 static
void f() {
    static int y = 2;  // 函数内 static
}
生成：
.local / .L / .hidden
或目标架构约定的 非导出符号
不参与链接器的 COMMON 合并
*原型 #define ASM_OUTPUT_ALIGNED_DECL_LOCAL(FILE, DECL, NAME, SIZE, ALIGN)  nvptx_output_aligned_decl (FILE, NAME, DECL, SIZE, ALIGN)
*/
static void outputAlignedDeclLocal_cb (TargetAsmOut *targetAsmOut,const_tree decl, const char *name, HOST_WIDE_INT size, unsigned align)
{
   TargetPtxAsmOut *self=(TargetPtxAsmOut *)targetAsmOut;
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(self);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsAsm *mtcsAsm=mtcs_target_get_asm(mtcsTarget);
   MtcsVar *mtcsVar=mtcs_target_get_var(mtcsTarget);

   FILE *back=mtcsAsm->asmFile;
   mtcsAsm->asmFile=mtcsAsm->asmVarDeclFile;
   n_debug("targetptxasmout.c -----nvptx.cc -----193-- nvptx_output_aligned 全局静态变量 decl decl:%p name:%s size:%d align:%d\n",
         decl,name,size,align);
   write_var_marker(self, true, TREE_PUBLIC (decl), name);
   /* If this is public, it is common.  The nearest thing we have to
   common is weak.  */
   fprintf (mtcsAsm->asmFile, "\t%s", TREE_PUBLIC (decl) ? ".weak " : "");
   nvptx_assemble_decl_begin(self, name, section_for_decl (self,decl),TREE_TYPE (decl), size, align);
   nvptx_assemble_decl_end(self);
   mtcsAsm->asmFile=back;
}

/**
 * user_label_prefix 声明在output.h中
 * extern const char *user_label_prefix;
 * 宏ASM_OUTPUT_LABELREF 缺省实现 原型 defaults.h
 * 需要在这里替换变量带有.号的变量名称
 */
static  void  outputLabelref_cb(TargetAsmOut *targetAsmOut,char *name)
{
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(targetAsmOut);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsAsm *mtcsAsm=mtcs_target_get_asm(mtcsTarget);
   MtcsOutput *mtcsOputput=mtcs_target_get_output(mtcsTarget);
   MtcsVar *mtcsVar=mtcs_target_get_var(mtcsTarget);

   fputs (mtcsOputput->user_label_prefix, mtcsAsm->asmFile);
   char *newName=mtcs_var_replace_dot(mtcsVar,name);
   if(newName){
      fputs (newName, mtcsAsm->asmFile);
      free(newName);
   }else{
      fputs (name, mtcsAsm->asmFile);
   }
}

//原型 #define ASM_OUTPUT_DEF(FILE,LABEL1,LABEL2)
static void outputDef_cb (TargetAsmOut *targetAsmOut,const char *label1,const char *label2)
{
//#define ASM_OUTPUT_DEF(FILE,LABEL1,LABEL2)  \
//  do                        \
//    {                       \
//      (void) (FILE);                \
//      (void) (LABEL1);              \
//      (void) (LABEL2);              \
//      gcc_unreachable ();           \
//    }                       \
//  while (0)
}

//原型 #define ASM_OUTPUT_ASCII(FILE, STR, LENGTH) nvptx有实现
static void outputAscii_cb(TargetAsmOut *targetAsmOut,const char *str, unsigned HOST_WIDE_INT size)
{
   TargetPtxAsmOut *self=(TargetPtxAsmOut *)targetAsmOut;
   n_debug("targetptxasmout.c -----nvptx.cc -----178-- nvptx_output_ascii %s size:%d\n",str,size);
   for (unsigned HOST_WIDE_INT i = 0; i < size; i++)
      nvptx_assemble_value (self,str[i], 1);
}

/* Emit a local array to hold some part of a conventional stack frame
   and initialize REGNO to point to it.  If the size is zero, it'll
   never be valid to dereference, so we can simply initialize to
   zero.  */
/* 发出一个本地数组来保存常规堆栈框架的某些部分，
并初始化 REGNO 使其指向该数组。如果大小为零，则
永远无法解除引用，因此我们可以简单地初始化为
零。*/
static void init_frame (TargetPtxAsmOut *self,int regno, unsigned align, unsigned size)
{
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(self);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsAsm *mtcsAsm=mtcs_target_get_asm(mtcsTarget);
   MtcsReg *mtcsReg=mtcs_target_get_reg(mtcsTarget);

   FILE *file=mtcsAsm->asmFile;
   char *regName=mtcs_reg_get_reg_name(mtcsReg,regno);
   n_debug("mtcsptx.c -----nvptx.cc -----23-- void init_frame regno:%d align:%d size:%d reg_name:%s\n",regno,align,size,regName);
   if (size)
      fprintf (file, "\t.local .align %d .b8 %s_ar[%u];\n",align, regName/*reg_names[regno]*/, size);
   fprintf (file, "\t.reg.u%d %s;\n",PTX_POINTER_SIZE, regName/*reg_names[regno]*/);
   fprintf (file, (size ? "\tcvta.local.u%d %s, %s_ar;\n" :  "\tmov.u%d %s, 0;\n"),
         PTX_POINTER_SIZE, regName,regName/*reg_names[regno], reg_names[regno]*/);
}

/* Emit soft stack frame setup sequence.  */
static void init_softstack_frame (TargetPtxAsmOut *self,FILE *file, unsigned alignment, HOST_WIDE_INT size)
{
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(self);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsReg *mtcsReg=mtcs_target_get_reg(mtcsTarget);
   MtcsFunc *mtcsFunc=mtcs_target_get_func(mtcsTarget);
   MtcsRtlData *mtcsRtlData=mtcs_func_get_rtl_data(mtcsFunc);

   //  struct ptx_machine_function *nvptxMachine=(struct ptx_machine_function *)mtcsFunc->machine;
   struct ptx_machine_function *nvptxMachine=(struct ptx_machine_function *)cfun->machine;

   /* Maintain 64-bit stack alignment.  */
   unsigned keep_align = PTX_BIGGEST_ALIGNMENT / BITS_PER_UNIT;
   size = ROUND_UP (size, keep_align);
   int bits = PTX_POINTER_SIZE;
   const char *reg_stack = mtcs_reg_get_reg_name(mtcsReg,PTX_STACK_POINTER_REGNUM);//reg_names[STACK_POINTER_REGNUM];
   const char *reg_frame = mtcs_reg_get_reg_name(mtcsReg,PTX_FRAME_POINTER_REGNUM);//reg_names[FRAME_POINTER_REGNUM];
   const char *reg_sspslot = mtcs_reg_get_reg_name(mtcsReg,PTX_SOFTSTACK_SLOT_REGNUM);//reg_names[SOFTSTACK_SLOT_REGNUM];
   const char *reg_sspprev = mtcs_reg_get_reg_name(mtcsReg,PTX_SOFTSTACK_PREV_REGNUM);//reg_names[SOFTSTACK_PREV_REGNUM];
   fprintf (file, "\t.reg.u%d %s;\n", bits, reg_stack);
   fprintf (file, "\t.reg.u%d %s;\n", bits, reg_frame);
   fprintf (file, "\t.reg.u%d %s;\n", bits, reg_sspslot);
   fprintf (file, "\t.reg.u%d %s;\n", bits, reg_sspprev);
   fprintf (file, "\t{\n");
   fprintf (file, "\t\t.reg.u32 %%fstmp0;\n");
   fprintf (file, "\t\t.reg.u%d %%fstmp1;\n", bits);
   fprintf (file, "\t\t.reg.u%d %%fstmp2;\n", bits);
   fprintf (file, "\t\tmov.u32 %%fstmp0, %%tid.y;\n");
   fprintf (file, "\t\tmul%s.u32 %%fstmp1, %%fstmp0, %d;\n", bits == 64 ? ".wide" : ".lo", bits / 8);
   fprintf (file, "\t\tmov.u%d %%fstmp2, __nvptx_stacks;\n", bits);

   /* Initialize %sspslot = &__nvptx_stacks[tid.y].  */
   fprintf (file, "\t\tadd.u%d %s, %%fstmp2, %%fstmp1;\n", bits, reg_sspslot);

   /* Initialize %sspprev = __nvptx_stacks[tid.y].  */
   fprintf (file, "\t\tld.shared.u%d %s, [%s];\n", bits, reg_sspprev, reg_sspslot);

   /* Initialize %frame = %sspprev - size.  */
   fprintf (file, "\t\tsub.u%d %s, %s, " HOST_WIDE_INT_PRINT_DEC ";\n",bits, reg_frame, reg_sspprev, size);

   /* Apply alignment, if larger than 64.  */
   if (alignment > keep_align)
      fprintf (file, "\t\tand.b%d %s, %s, %d;\n",bits, reg_frame, reg_frame, -alignment);

   //size = crtl->outgoing_args_size;
   size =mtcsRtlData/*!crtl*/->outgoing_args_size.coeffs[0];
   gcc_assert (size % keep_align == 0);

   /* Initialize %stack.  */
   fprintf (file, "\t\tsub.u%d %s, %s, " HOST_WIDE_INT_PRINT_DEC ";\n",bits, reg_stack, reg_frame, size);

   if (!mtcsRtlData/*!crtl*/->is_leaf)
      fprintf (file, "\t\tst.shared.u%d [%s], %s;\n",bits, reg_sspslot, reg_stack);
   fprintf (file, "\t}\n");
   nvptxMachine->has_softstack = true;
   self->need_softstack_decl = true;
}

/* Emit code to initialize the REGNO predicate register to indicate
   whether we are not lane zero on the NAME axis.  */
static void nvptx_init_axis_predicate (TargetPtxAsmOut *self,FILE *file, int regno, const char *name)
{
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(self);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsPtx *mtcsPtx=(MtcsPtx *)mtcsTarget;
   MtcsFunc *mtcsFunc=mtcs_target_get_func(mtcsTarget);

   struct ptx_machine_function *nvptxMachine=(struct ptx_machine_function *)cfun->machine;
   n_debug("mtcsptx.c -----nvptx.cc -----24-- void nvptx_init_axis_predicate (FILE *file, int regno, const char *name)\n");
   fprintf (file, "\t{\n");
   fprintf (file, "\t\t.reg.u32\t%%%s;\n", name);
   if (strcmp (name, "x") == 0 && nvptxMachine->red_partition){
      fprintf (file, "\t\t.reg.u64\t%%t_red;\n");
      fprintf (file, "\t\t.reg.u64\t%%y64;\n");
   }
   fprintf (file, "\t\tmov.u32\t%%%s, %%tid.%s;\n", name, name);
   fprintf (file, "\t\tsetp.ne.u32\t%%r%d, %%%s, 0;\n", regno, name);
   if (strcmp (name, "x") == 0 && nvptxMachine->red_partition){
      fprintf (file, "\t\tcvt.u64.u32\t%%y64, %%tid.y;\n");
      fprintf (file, "\t\tcvta.shared.u64\t%%t_red, __vector_red;\n");
      fprintf (file, "\t\tmad.lo.u64\t%%r%d, %%y64, %d, %%t_red; "
      "// vector reduction buffer\n", REGNO (nvptxMachine->red_partition), self->vector_red_partition);
   }
   /* Verify vector_red_size.  */
   gcc_assert (self->vector_red_partition * mtcs_ptx_get_mach_max_workers/*!nvptx_mach_max_workers*/(mtcsPtx)
                        <= self->vector_red_size);
   fprintf (file, "\t}\n");
}

/* Emit code to initialize predicate and master lane index registers for
   -muniform-simt code generation variant.  */
static void nvptx_init_unisimt_predicate (TargetPtxAsmOut *self,FILE *file)
{
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(self);
   MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
   MtcsFunc *mtcsFunc=mtcs_target_get_func(mtcsTarget);
   MtcsEmit *mtcsEmit=mtcs_target_get_emit(mtcsTarget);

   struct ptx_machine_function *nvptxMachine=(struct ptx_machine_function *)cfun->machine;

   n_debug("mtcsptx.c -----nvptx.cc -----26-- void nvptx_init_unisimt_predicate (FILE *file)\n");

   nvptxMachine->unisimt_location = mtcs_emit_gen_reg_rtx/*!gen_reg_rtx*/(mtcsEmit,mtcs_mode_get_Pmode(mtcsMode));
   int loc = REGNO (nvptxMachine->unisimt_location);
   int bits = POINTER_SIZE;
   fprintf (file, "\t.reg.u%d %%r%d;\n", bits, loc);
   fprintf (file, "\t{\n");
   fprintf (file, "\t\t.reg.u32 %%ustmp0;\n");
   fprintf (file, "\t\t.reg.u%d %%ustmp1;\n", bits);
   fprintf (file, "\t\tmov.u32 %%ustmp0, %%tid.y;\n");
   fprintf (file, "\t\tmul%s.u32 %%ustmp1, %%ustmp0, 4;\n",
   bits == 64 ? ".wide" : ".lo");
   fprintf (file, "\t\tmov.u%d %%r%d, __nvptx_uni;\n", bits, loc);
   fprintf (file, "\t\tadd.u%d %%r%d, %%r%d, %%ustmp1;\n", bits, loc, loc);
   if (nvptxMachine->unisimt_predicate){
      int master = REGNO (nvptxMachine->unisimt_master);
      int pred = REGNO (nvptxMachine->unisimt_predicate);
      fprintf (file, "\t\tld.shared.u32 %%r%d, [%%r%d];\n", master, loc);
      if (nvptxMachine->unisimt_outside_simt_predicate){
         int pred_outside_simt = REGNO (nvptxMachine->unisimt_outside_simt_predicate);
         fprintf (file, "\t\tsetp.eq.u32 %%r%d, %%r%d, 0;\n",pred_outside_simt, master);
      }
      fprintf (file, "\t\tmov.u32 %%ustmp0, %%laneid;\n");
      /* Compute 'master lane index' as 'laneid & __nvptx_uni[tid.y]'.  */
      fprintf (file, "\t\tand.b32 %%r%d, %%r%d, %%ustmp0;\n", master, master);
      /* Compute predicate as 'tid.x == master'.  */
      fprintf (file, "\t\tsetp.eq.u32 %%r%d, %%r%d, %%ustmp0;\n", pred, master);
   }
   fprintf (file, "\t}\n");
   self->need_unisimt_decl = true;
}

/* Emit code to initialize OpenACC worker broadcast and synchronization
   registers.  */
static void nvptx_init_oacc_workers (FILE *file)
{
//    n_debug("mtcsptx.c -----nvptx.cc -----25-- void nvptx_init_oacc_workers (FILE *file)\n");
//
//  fprintf (file, "\t{\n");
//  fprintf (file, "\t\t.reg.u32\t%%tidy;\n");
//  if (cfun->machine->bcast_partition){
//      fprintf (file, "\t\t.reg.u64\t%%t_bcast;\n");
//      fprintf (file, "\t\t.reg.u64\t%%y64;\n");
//  }
//  fprintf (file, "\t\tmov.u32\t\t%%tidy, %%tid.y;\n");
//  if (cfun->machine->bcast_partition){
//      fprintf (file, "\t\tcvt.u64.u32\t%%y64, %%tidy;\n");
//      fprintf (file, "\t\tadd.u64\t\t%%y64, %%y64, 1; // vector ID\n");
//      fprintf (file, "\t\tcvta.shared.u64\t%%t_bcast, __oacc_bcast;\n");
//      fprintf (file, "\t\tmad.lo.u64\t%%r%d, %%y64, %d, %%t_bcast; "
//           "// vector broadcast offset\n", REGNO (cfun->machine->bcast_partition), oacc_bcast_partition);
//    }
//  /* Verify oacc_bcast_size.  */
//  gcc_assert (oacc_bcast_partition * (nvptx_mach_max_workers () + 1) <= oacc_bcast_size);
//  if (cfun->machine->sync_bar)
//    fprintf (file, "\t\tadd.u32\t\t%%r%d, %%tidy, 1; "
//         "// vector synchronization barrier\n",REGNO (cfun->machine->sync_bar));
//  fprintf (file, "\t}\n");
}

/* If MODE should be treated as two registers of an inner mode, return
   that inner mode.  Otherwise return VOIDmode.  */
static nuint maybe_split_mode ( TargetPtxAsmOut *self,mtcs_mode mode)
{
   MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(self);

   if (mtcs_mode_is_complex_p (mtcsMode,mode))
      return mtcs_mode_get_inner/*GET_MODE_INNER */(mtcsMode,mode);
   if (mode == mtcsMode->modes.M_TImode)
      return mtcsMode->modes.M_DImode;
   return mtcsMode->modes.M_VOIDmode;
}

/* Return true if mode should be treated as two registers.  */

static bool split_mode_p (TargetPtxAsmOut *self,machine_mode mode)
{
  return maybe_split_mode(self,mode) != VOIDmode;
}


/**
 * 实现ASM_DECLARE_FUNCTION_NAME(FILE, NAME, DECL)
 * 来自nvptx_declare_function_name
 * https://findhao.net/easycoding/2064
 */
static void declareFunctionName_cb (TargetAsmOut *targetAsmOut, const char *name, const_tree decl)
{
  n_debug("mtcsptx.c -----nvptx.cc -----27-- void nvptx_declare_function_name name:%s\n",name);
  TargetPtxAsmOut *self=(TargetPtxAsmOut *)targetAsmOut;
  MtcsMode *mtcsMode=MTCS_GET_MODE_OBJECT(self);
  MtcsTarget *mtcsTarget=(MtcsTarget *)mtcsMode->target;
  MtcsAsm *mtcsAsm=mtcs_target_get_asm(mtcsTarget);
  MtcsReg *mtcsReg=mtcs_target_get_reg(mtcsTarget);
  MtcsPtxOutput *mtcsPtxOutput=(MtcsPtxOutput *)mtcs_target_get_output(mtcsTarget);
  MtcsFunc *mtcsFunc=mtcs_target_get_func(mtcsTarget);
  MtcsPtxFunc *mtcsPtxFunc=(MtcsPtxFunc *)mtcsFunc;
  MtcsRtlData *mtcsRtlData=mtcs_func_get_rtl_data(mtcsFunc);
  MtcsTree *mtcsTree=mtcs_target_get_tree(mtcsTarget);
  MtcsOptions *mtcsOptions=mtcs_target_get_options(mtcsTarget);
  MtcsPtxOptions *mtcsPtxOptions=(MtcsPtxOptions *)mtcsOptions;

  struct ptx_machine_function *nvptxMachine=(struct ptx_machine_function *)cfun->machine;

  FILE *file=mtcsAsm->asmFile;
  tree fntype = TREE_TYPE (decl);
  tree result_type = TREE_TYPE (fntype);
  int argno = 0;
  bool force_public = false;

  /* For reverse-offload 'nohost' functions: In order to be collectable in
     '$offload_func_table', cf. mkoffload.cc, the function has to be visible. */
  /*mtcs 注意屏蔽不一定正确
  if (lookup_attribute ("omp target device_ancestor_nohost",DECL_ATTRIBUTES (decl)))
    force_public = true;
  if (lookup_attribute ("omp target entrypoint", DECL_ATTRIBUTES (decl))
          && !lookup_attribute ("oacc function", DECL_ATTRIBUTES (decl))){
      char *buf = (char *) alloca (strlen (name) + sizeof ("$impl"));
      sprintf (buf, "%s$impl", name);
      write_omp_entry (file, name, buf);
      name = buf;
  }
  */
  //找是否有 mtcs visible属性
  force_public = mtcs_info_is_visible(decl);
  n_debug("mtcsptx.c -----nvptx.cc -----27aa 是否函数可见:%s force_public:%d 写入函数声明\n",name,force_public);

  /* We construct the initial part of the function into a string
     stream, in order to share the prototype writing code.  */
  NString *str=n_string_new("");
  //函数声明与定义，生成
  /*
  // BEGIN GLOBAL FUNCTION DECL: _Z8TestMtcs7setDataEPN8TestMtcsEPf$cuda$0
  .visible .entry _Z8TestMtcs7setDataEPN8TestMtcsEPf$cuda$0 (.param.u64 %in_ar0, .param.u64 %in_ar1);

  // BEGIN GLOBAL FUNCTION DEF: _Z8TestMtcs7setDataEPN8TestMtcsEPf$cuda$0
  .visible .entry _Z8TestMtcs7setDataEPN8TestMtcsEPf$cuda$0 (.param.u64 %in_ar0, .param.u64 %in_ar1)
  */
  char *fndeclSt=mtcs_ptx_func_write_fn_proto/*!write_fn_proto*/(mtcsPtxFunc,name, decl, force_public);
  n_debug("mtcsptx.c -----nvptx.cc -----27bb 开始写入函数体 x_nvptx_softstack_size:%d\n",mtcsPtxOptions->x_nvptx_softstack_size);
  n_string_append(str,fndeclSt);
  n_string_append(str,"\n");
  n_string_append(str,"{\n");
  n_debug("mtcsptx.c -----nvptx.cc -----27cc 写入返回值类型\n");

  bool return_in_mem =mtcs_ptx_func_write_return_type/*!write_return_type*/(mtcsPtxFunc,str, false, result_type);
  if (return_in_mem)
    //argno = write_arg_type (self,str, 0, argno, ptr_type_node, true);
    argno = mtcs_ptx_func_write_arg_type (mtcsPtxFunc,str, 0, argno, mtcs_ptr_type_node, true);

  /* Declare and initialize incoming arguments.  */
  tree args = TYPE_ARG_TYPES (fntype);
  bool prototyped = true;
  if (!args){
      args = DECL_ARGUMENTS (decl);
      prototyped = false;
  }

  //参数写入寄存器,生成
  /*
  .reg.u64 %ar0;
    ld.param.u64 %ar0, [%in_ar0];
    .reg.u64 %ar1;
    ld.param.u64 %ar1, [%in_ar1];
    */
  for (; args != NULL_TREE; args = TREE_CHAIN (args)){
      tree type = prototyped ? TREE_VALUE (args) : TREE_TYPE (args);
      argno = mtcs_ptx_func_write_arg_type/*!write_arg_type*/(mtcsPtxFunc,str, 0, argno, type, prototyped);
  }
  /* 如果 TYPE 具有可变参数列表，则返回 true。 */
  if (stdarg_p (fntype))
    argno = mtcs_ptx_func_write_arg_type/*!write_arg_type*/(mtcsPtxFunc,str, PTX_ARG_POINTER_REGNUM, argno, mtcs_ptr_type_node,true);

  if (DECL_STATIC_CHAIN (decl) || nvptxMachine/*!cfun->machine*/->has_chain)
      mtcs_ptx_func_write_arg_type/*!write_arg_type*/(mtcsPtxFunc,str,
            PTX_STATIC_CHAIN_REGNUM,DECL_STATIC_CHAIN (decl) ? argno : -1, mtcs_ptr_type_node,true);

  n_debug("mtcsptx.c ----内容是---:\n%s\n",str->str);
  fprintf (file, "%s", str->str);
  n_string_free(str,TRUE);
  n_debug("mtcsptx.c -----nvptx.cc -----27dd !crtl->is_leaf:%d\n",mtcsRtlData/*!crtl*/->is_leaf);
  uint stack_alignment_needed=mtcs_rtl_data_get_stack_alignment_needed(mtcsRtlData);
  /* Usually 'crtl->is_leaf' is computed during register allocator
     initialization (which is not done on NVPTX) or for pressure-sensitive
     optimizations.  Initialize it here, except if already set.  */
  if (!mtcsRtlData/*!crtl*/->is_leaf)
     mtcsRtlData/*!crtl*/->is_leaf = mtcs_output_leaf_function_p/*!leaf_function_p*/((MtcsOutput *)mtcsPtxOutput);
  n_debug("mtcsptx.c -----nvptx.cc -----27ee !crtl->is_leaf:%d crtl->stack_alignment_needed:%d\n",
        mtcsRtlData/*!crtl*/->is_leaf,mtcsRtlData/*!crtl*/->stack_alignment_needed);

  HOST_WIDE_INT sz = mtcs_func_get_frame_size/*get_frame_size()*/ (mtcsFunc).coeffs[0];
  bool need_frameptr = sz || nvptxMachine/*!cfun->machine*/->has_chain;
  int alignment =mtcs_rtl_data_get_stack_alignment_needed(mtcsRtlData)/*crtl->stack_alignment_needed*/ / BITS_PER_UNIT;
  n_debug("mtcsptx.c -----nvptx.cc -----27附加need_frameptr:%d nvptxMachine->has_variadic:%d cfun->calls_alloca:%d is_leaf:%d has_simtreg:%d sz:%d\n",
          need_frameptr,nvptxMachine->has_variadic,cfun->calls_alloca,crtl->is_leaf,nvptxMachine->has_simtreg,sz);

  if (!mtcs_options_target_soft_stack/*!TARGET_SOFT_STACK*/(mtcsOptions)){
      /* Declare a local var for outgoing varargs.  */
      n_debug("mtcsptx.c -----nvptx.cc -----27ff !TARGET_SOFT_STACK nvptxMachine->has_variadic:%d need_frameptr:%d\n",
            nvptxMachine->has_variadic,need_frameptr);
      //初始化栈桢，生成
      /*
       * .local .align 8 .b8 %stack_ar[16];
       * .reg.u64 %stack;
       *  cvta.local.u64 %stack, %stack_ar;
       */
      if (nvptxMachine->has_variadic)
          init_frame(self,PTX_STACK_POINTER_REGNUM,PTX_UNITS_PER_WORD, mtcsRtlData/*!crtl*/->outgoing_args_size.coeffs[0]);

      /* Declare a local variable for the frame.  Force its size to be
     DImode-compatible.  */
      if (need_frameptr)
          init_frame(self,PTX_FRAME_POINTER_REGNUM, alignment,
                ROUND_UP (sz, mtcs_mode_get_size(mtcsMode,mtcsMode->modes.M_DImode)/*GET_MODE_SIZE(DImode)*/));
  //}else if (need_frameptr || cfun->machine->has_variadic || cfun->calls_alloca  || (cfun->machine->has_simtreg && !crtl->is_leaf))
  }else if (need_frameptr || nvptxMachine->has_variadic || cfun->calls_alloca
        || (nvptxMachine->has_simtreg && !mtcsRtlData/*!crtl*/->is_leaf)){
      n_debug("mtcsptx.c -----nvptx.cc -----27gg\n");
      init_softstack_frame(self,file, alignment, sz);
  }

  if (nvptxMachine/*!cfun->machine*/->has_simtreg){
      unsigned HOST_WIDE_INT &simtsz = nvptxMachine->simt_stack_size;
      unsigned HOST_WIDE_INT &align = nvptxMachine->simt_stack_align;
      align = MAX (align, mtcs_mode_get_size/*GET_MODE_SIZE*/(mtcsMode, mtcsMode->modes.M_DImode));
      n_debug("mtcsptx.c -----nvptx.cc -----27hh cfun->machine->has_simtreg simtsz:%d align:%d\n",simtsz,align);
      if (!mtcsRtlData/*!crtl*/->is_leaf || cfun->calls_alloca){
          simtsz = HOST_WIDE_INT_M1U;
          n_debug("mtcsptx.c -----nvptx.cc -----27hh-1 cfun->machine->has_simtreg simtsz:%d\n",simtsz);

      }
      if (simtsz == HOST_WIDE_INT_M1U){
          simtsz = mtcsPtxOptions->x_nvptx_softstack_size;// nvptx_softstack_size;每个平台的options.h中定义 struct gcc_options
          n_debug("mtcsptx.c -----nvptx.cc -----27hh-2 cfun->machine->has_simtreg simtsz:%d\n",simtsz);

      }
      if (nvptxMachine->has_softstack){
          simtsz += POINTER_SIZE / 8;
          n_debug("mtcsptx.c -----nvptx.cc -----27hh-3 cfun->machine->has_simtreg simtsz:%d\n",simtsz);

      }
      simtsz = ROUND_UP (simtsz, mtcs_mode_get_size/*!GET_MODE_SIZE*/(mtcsMode,mtcsMode->modes.M_DImode));
      n_debug("mtcsptx.c -----nvptx.cc -----27hh-4 cfun->machine->has_simtreg simtsz:%d\n",simtsz);

      if (align >mtcs_mode_get_size/*!GET_MODE_SIZE*/(mtcsMode,mtcsMode->modes.M_DImode)){
          simtsz += align - mtcs_mode_get_size/*!GET_MODE_SIZE*/ (mtcsMode,mtcsMode->modes.M_DImode);
          n_debug("mtcsptx.c -----nvptx.cc -----27hh-5 cfun->machine->has_simtreg simtsz:%d\n",simtsz);
      }
      n_debug("mtcsptx.c -----nvptx.cc -----27hh-6 cfun->machine->has_simtreg simtsz:%d\n",simtsz);
      if (simtsz)
          fprintf (file, "\t.local.align 8 .b8 %%simtstack_ar["HOST_WIDE_INT_PRINT_DEC "];\n", simtsz);
  }
  /* Restore the vector reduction partition register, if necessary.
     FIXME: Find out when and why this is necessary, and fix it.  */
  if (nvptxMachine/*!cfun->machine*/->red_partition){
      n_debug("mtcsptx.c -----nvptx.cc -----27ii nvptxMachine->red_partition:%d\n",nvptxMachine->red_partition);
      //regno_reg_rtx[REGNO (cfun->machine->red_partition)] = cfun->machine->red_partition;
      mtcsRtlData->regno_reg_rtx/*!regno_reg_rtx*/[REGNO (nvptxMachine->red_partition)] = nvptxMachine->red_partition;
  }
  //regno_reg_rtx 在emit-rtl.cc 方法gen_reg_rtx中生成
  /* Declare the pseudos we have as ptx registers.  */
  int  lastVirtualRegister= mtcs_reg_get_last_virtual_regno/*!LAST_VIRTUAL_REGISTER*/(mtcsReg);

  int maxregs = mtcs_func_max_reg_num/*!max_reg_num*/(mtcsFunc);//max_reg_num是主机的maxregs 不是ptx的
  for (int i = lastVirtualRegister + 1; i < maxregs; i++){
      if (mtcsRtlData->regno_reg_rtx/*!regno_reg_rtx*/[i] != const0_rtx){
          machine_mode mode = mtcs_rtl_data_get_pseudo_regno_mode/*!PSEUDO_REGNO_MODE*/(mtcsRtlData,i);
          mtcs_mode split = maybe_split_mode(self,mode);
          n_debug("mtcsptx.c -----nvptx.cc -----27jj i:%d maxregs:%d  mtcs_mode:%d %s mtcsRegno:%d split:%d\n",
                  i,maxregs,mode,mtcs_mode_get_name(mtcsMode,mode),i,split);
          mtcs_print_rtl(stderr,mtcsRtlData->regno_reg_rtx/*!regno_reg_rtx*/[i]);
          n_debug("\mtcsptx.c regno_reg_rtx print end \n");
          if (split_mode_p(self,mode)){
            n_debug("mtcsptx.c -----nvptx.cc -----27jjvvv-- i:%d mode:%d\n",i,mode);
             mode = split;
          }
          //下面三行生成汇编 .reg.u32 %r30;
          fprintf (file, "\t.reg%s ", mtcs_mode_get_type (mtcsMode,mode, true));
          mtcs_ptx_output_output_reg (mtcsPtxOutput,i, split, -2);
          fprintf (file, ";\n");
      }
  }
  n_debug("mtcsptx.c -----nvptx.cc -----27----结束第一部分\n");

  /* Emit axis predicates. */
//  if (cfun->machine->axis_predicate[0])
//    nvptx_init_axis_predicate (file, REGNO (cfun->machine->axis_predicate[0]), "y");
//  if (cfun->machine->axis_predicate[1])
//    nvptx_init_axis_predicate (file, REGNO (cfun->machine->axis_predicate[1]), "x");
//  if (cfun->machine->unisimt_predicate|| (cfun->machine->has_simtreg && !crtl->is_leaf))
//    nvptx_init_unisimt_predicate (file);
//  if (cfun->machine->bcast_partition || cfun->machine->sync_bar)
//    nvptx_init_oacc_workers (file);

  if (nvptxMachine->axis_predicate[0])
    nvptx_init_axis_predicate(self,file, REGNO (nvptxMachine->axis_predicate[0]), "y");
  if (nvptxMachine->axis_predicate[1])
    nvptx_init_axis_predicate(self,file, REGNO (nvptxMachine->axis_predicate[1]), "x");
  if (nvptxMachine->unisimt_predicate|| (nvptxMachine->has_simtreg && !mtcsRtlData/*!crtl*/->is_leaf))
    nvptx_init_unisimt_predicate (self,file);
  if (nvptxMachine->bcast_partition || nvptxMachine->sync_bar)
    nvptx_init_oacc_workers (file);
}

/**
 * nvptx 的TARGET_ASM_MARK_DECL_PRESERVEDP的实现是空的
 */
static void markDeclPreserved_cb (TargetAsmOut *targetAsmOut,const char *name)
{
}


//struct asm_int_op
//{
//  const char *hi;
//  const char *psi;
//  const char *si;
//  const char *pdi;
//  const char *di;
//  const char *pti;
//  const char *ti;
//};
//asm_int_op  aligned_op:
//   hi:   .short
//   psi:(null)
//   si:   .long
//   pdi:(null)
//   di:(null)
//   pti:(null)
//   ti:(null)
//asm_int_op  unaligned_op:
//   hi:(null)
//   psi:(null)
//   si:(null)
//   pdi:(null)
//   di:(null)
//   pti:(null)
//   ti:(null)
//targetm.asm_out.byte_op    .byte
//原型 #define TARGET_ASM_ALIGNED_INT_OP #define TARGET_ASM_UNALIGNED_INT_OP target-def.h
static void init_asm_int_op(TargetPtxAsmOut *self)
{
   TargetAsmOut *targetAsmOut=(TargetAsmOut *)self;

   targetAsmOut->aligned_op.hi="\t.short\t"; //原型 TARGET_ASM_ALIGNED_HI_OP target-def.h
   targetAsmOut->aligned_op.psi=NULL;
   targetAsmOut->aligned_op.si="\t.long\t";  //原型 TARGET_ASM_ALIGNED_SI_OP target-def.h
   targetAsmOut->aligned_op.pdi=NULL;
   targetAsmOut->aligned_op.di=NULL;
   targetAsmOut->aligned_op.pti=NULL;
   targetAsmOut->aligned_op.ti=NULL;

   targetAsmOut->unaligned_op.hi=NULL;
   targetAsmOut->unaligned_op.psi=NULL;
   targetAsmOut->unaligned_op.si=NULL;
   targetAsmOut->unaligned_op.pdi=NULL;
   targetAsmOut->unaligned_op.di=NULL;
   targetAsmOut->unaligned_op.pti=NULL;
   targetAsmOut->unaligned_op.ti=NULL;
   targetAsmOut->byte_op ="\t.byte\t";
}



static void targetPtxAsmOutInit(TargetPtxAsmOut *self)
{
   TargetAsmOut *targetAsmOut=(TargetAsmOut *)self;
   //原型targetm.asm_out.print_operand_address #define TARGET_PRINT_OPERAND_ADDRESS default_print_operand_address
   targetAsmOut->print_operand_address=printOperandAddress_cb;
   //原型targetm.asm_out.print_operand_address #define TARGET_PRINT_OPERAND_ADDRESS default_print_operand_address
   targetAsmOut->print_operand=printOperand_cb;
   //原型  targetm.asm_out.file_start ();#define TARGET_ASM_FILE_START nvptx_file_start
   targetAsmOut->file_start=fileStart_cb;
   //原型 targetm.asm_out.declare_constant_name (asm_out_file, label, exp, size); #define TARGET_ASM_DECLARE_CONSTANT_NAME default_asm_declare_constant_name
   targetAsmOut->declare_constant_name=declareConstantName_cb;
   //原型 TARGET_ASM_DECL_END 无缺省实现
   targetAsmOut->decl_end=declEnd_cb;
   //原型targetm.asm_out.globalize_label (file, name); #define TARGET_ASM_GLOBALIZE_LABEL default_globalize_label
   targetAsmOut->globalize_label=globalizeLabel_cb;
   //原型  targetm.asm_out.print_operand_punct_valid_p ((unsigned char) *p)
   //#define TARGET_PRINT_OPERAND_PUNCT_VALID_P nvptx_print_operand_punct_valid_p
   targetAsmOut->print_operand_punct_valid_p=printOperandPunctValidP_cb;
   //原型 targetm.asm_out.file_end (); #define TARGET_ASM_FILE_END nvptx_file_end
   targetAsmOut->file_end=fileEnd_cb;
   //原型 targetm.asm_out.assemble_undefined_decl (asm_out_file, name, decl); #define TARGET_ASM_ASSEMBLE_UNDEFINED_DECL nvptx_assemble_undefined_decl
   targetAsmOut->assemble_undefined_decl=assembleUndefinedDecl_cb;
   //原型 targetm.asm_out.integer#define TARGET_ASM_INTEGER nvptx_assemble_integer
   targetAsmOut->integer=integer_cb;
   //原型 targetm.asm_out.globalize_decl_name (asm_out_file, decl);#define TARGET_ASM_GLOBALIZE_DECL_NAME default_globalize_decl_name
   targetAsmOut->globalize_decl_name=globalizeDeclName_cb;

   //gcc 旧实现采用的宏，原来声明在MtcsTarget，现在移到 TargetAsmOut
   //旧实现中用到宏的有 1.ASM_OUTPUT_SKIP ASM_OUTPUT_ALIGNED_DECL_COMMON ASM_DECLARE_OBJECT_NAME ASM_OUTPUT_ALIGNED_DECL_LOCAL
   //原型 #define ASM_OUTPUT_SKIP(FILE, N) nvptx有实现
   targetAsmOut->output_skip=outputSkip_cb;
   //原型 #define ASM_OUTPUT_ALIGNED_DECL_COMMON(FILE, DECL, NAME, SIZE, ALIGN)   nvptx有实现
   targetAsmOut->output_aligned_decl_common=outputAlignedDeclCommon_cb;
   //原型 #define ASM_DECLARE_OBJECT_NAME(FILE, NAME, DECL)  nvptx_declare_object_name (FILE, NAME, DECL)
   targetAsmOut->declare_object_name=declareObjectName_cb;
   //原型 #define ASM_OUTPUT_ALIGNED_DECL_LOCAL(FILE, DECL, NAME, SIZE, ALIGN)  nvptx_output_aligned_decl (FILE, NAME, DECL, SIZE, ALIGN)
   targetAsmOut->output_aligned_decl_local=outputAlignedDeclLocal_cb;
   //ASM_OUTPUT_LABELREF 缺省实现，AMD的gcn实现不同
   targetAsmOut->output_labelref=outputLabelref_cb;
   //原型 #define ASM_OUTPUT_DEF(FILE,LABEL1,LABEL2)
   targetAsmOut->output_def = outputDef_cb;
   //原型 #define ASM_OUTPUT_ASCII(FILE, STR, LENGTH) nvptx有实现
   targetAsmOut->output_ascii=outputAscii_cb;
   //实现ASM_DECLARE_FUNCTION_NAME(FILE, NAME, DECL)
   targetAsmOut->declare_function_name=declareFunctionName_cb;
   //TARGET_ASM_MARK_DECL_PRESERVED gcc中的实现是hook_void_constcharptr 声明在gcc/targetdef
   targetAsmOut->mark_decl_preserved =markDeclPreserved_cb;
   //------结束类方法赋值-----------------
   init_asm_int_op(self);
}

TargetPtxAsmOut *target_ptx_asm_out_new(MtcsMode *mtcsMode)
{
   TargetPtxAsmOut *self = n_slice_alloc0 (sizeof(TargetPtxAsmOut));
   mtcs_component_set_mode((MtcsComponent*)self,mtcsMode);
   target_asm_out_init((TargetAsmOut*)self);
   targetPtxAsmOutInit(self);
   return self;
}

